project:
  type: website
  output-dir: docs

website:
  title: "Legume Nutrient Dashboard"
  site-url: https://Tubbers03.github.io/Individual-Legume-Data/
  site-path: /Individual-Legume-Data/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Documentation.qmd
        text: Documentation
      - href: Tutorial.qmd
        text: Tutorial
      - href: TechnicalReport.qmd
        text: Technical Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Exclude unnecessary files from the build
exclude:
  - myenv/
  - "*.ipynb"
  - ".quarto/"



