project:
  type: website
  output-dir: docs

website:
  title: "Legume Nutrient Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Documentation.qmd
        text: Documentation
      - href: Tutorial.qmd
        text: Tutorial
      - href: TechnicalReport.qmd
        text: Final Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# Exclude virtual environment and unnecessary files
exclude:
  - myenv/
  - "*.ipynb"
  - ".quarto/"
  - "dist/"
  - "__pycache__/"
  - "*.pyc"



